services:
  - type: web
    name: kopi-kuba
    runtime: node
    plan: free
    startCommand: npm start
    buildCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        scope: project
      - key: EMAIL_PASS
        scope: project
    staticSite:
      rootDir: ./
      routes:
        - path: /
          rewrite: /index.html
        - path: /login
          rewrite: /login.html
        - path: /register
          rewrite: /register.html
